# Generated by Django 4.0.6 on 2022-07-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_controller.deliveryman'),
        ),
    ]
