# Generated by Django 4.0.6 on 2022-08-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0003_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
