# Generated by Django 4.0.6 on 2022-08-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='coord',
            field=models.CharField(default='', max_length=50),
        ),
    ]
