# Generated by Django 4.0.6 on 2022-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0009_alter_inventory_inventory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
