# Generated by Django 4.0.6 on 2022-08-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0011_remove_auction_product_auction_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('auction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='global_controller.auction')),
                ('inventory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='global_controller.inventory')),
            ],
        ),
    ]
