# Generated by Django 4.0.6 on 2022-08-24 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0014_alter_auction_inventory_alter_packageitem_auction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='global_controller.bid'),
        ),
    ]
