# Generated by Django 4.0.6 on 2022-08-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0015_remove_bid_auction_auction_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubman',
            name='designation',
        ),
    ]
