# Generated by Django 4.0.6 on 2022-08-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0016_remove_hubman_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_order',
            name='auction',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='global_controller.auction_order'),
        ),
    ]
