# Generated by Django 4.0.6 on 2022-08-28 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0017_remove_auction_order_auction_auction_auction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='current_hub',
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='current_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='global_controller.hub'),
        ),
    ]
