# Generated by Django 4.0.6 on 2022-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0017_remove_auction_order_auction_auction_auction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
