# Generated by Django 4.0.6 on 2022-08-28 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0018_remove_deliveryman_current_hub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_order',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='is_package',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='quantity',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='global_controller.order'),
        ),
        migrations.DeleteModel(
            name='Auction_Order',
        ),
    ]
