# Generated by Django 4.0.6 on 2022-08-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_controller', '0019_remove_auction_auction_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coord',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
