from django.contrib import admin
from .models import *

admin.site.register(UserType)
admin.site.register(User)
admin.site.register(Hub)
admin.site.register(Hubman)
admin.site.register(Customer)
admin.site.register(Seller)
admin.site.register(Brand)
admin.site.register(Category)
admin.site.register(Product)
admin.site.register(Deliveryman)
admin.site.register(Order_Status)
admin.site.register(Transaction)
admin.site.register(Order_Set)
admin.site.register(Order)
admin.site.register(Return)
admin.site.register(Inventory)
admin.site.register(Auction)
admin.site.register(Bid)
admin.site.register(Auction_Order)
admin.site.register(PackageItem)